name: Quarto Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: d-morrison/gha/.github/workflows/quarto-publish.yml@v1
